version: '3'
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=216.155.157.239
      - PASSWORD=admin001
      - WG_DEFAULT_ADDRESS=10.0.10.x
      - WG_DEFAULT_DNS=8.8.8.8,223.5.5.5
      - WG_PERSISTENT_KEEPALIVE=25
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
